### ISSUE TITLE
The hmssdk Example Flutter app crashes on xiaommi phone.

### ISSUE THREAD

**Issue by Nasseh123** [ygit/ygit#1]
Hey, @ygit I have an issue while testing the hmssdk example app on a xiaommi phone. It keeps on crashing when I turn on the camera during the preview or when am in a meeting. Any leads to this?

**Comment by ygit** [comment]
hey @Nasseh123 

Does the crash only happen when you try to enable the Camera? Can you share any error logs? Are you able to join the Room where audio communication works?

If possible, can you share the Room Meeting Link you are using to Join?

Ensure you have added Android Device Permissions [as mentioned here](https://www.100ms.live/docs/flutter/v2/features/integration#android).

You can try running this [Basic Sample App](https://github.com/100mslive/100ms-flutter/tree/main/sample%20apps/flutter-quickstart-app) on your system.

You can try out the Released version of the apps. The stable one from [Google Play Store here](https://play.google.com/store/apps/details?id=live.hms.flutter) or our [Beta version from Firebase here](https://appdistribution.firebase.dev/i/b623e5310929ab70).

**Comment by Nasseh123** [comment]
Yes, the crash only happens when I enable the Camera. It both happens with the released version of the app  on Google Play Store and also the  [Example App](https://github.com/100mslive/100ms-flutter/tree/main/example)
I have also all the Android Device Permissions added as required.

Bellow find the logs I captured earlier yesterday.

`                   libc  W  Access denied finding property "persist.vendor.camera.privapp.list"
    CameraExtImplXiaoMi  D  initCameraDevice: 1
      CameraDevice-JV-1  D  waitUntilIdle: E. id = 1
                         D  waitUntilIdle: X
#flutter/platform_views  E  Failed to handle method call
                         E  java.lang.RuntimeException: Adding window failed
                         E      at android.view.ViewRootImpl.setView(ViewRootImpl.java:1205)
                         E      at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:403)
                         E      at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:134)
                         E      at android.app.Dialog.show(Dialog.java:354)
                         E      at android.app.Presentation.show(Presentation.java:279)
                         E      at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:119)
                         E      at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:64)
                         E      at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:267)
                         E      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
                         E      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
                         E      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
                         E      at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
                         E      at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
                         E      at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
                         E      at android.os.Handler.handleCallback(Handler.java:938)
                         E      at android.os.Handler.dispatchMessage(Handler.java:99)
                         E      at android.os.Looper.loopOnce(Looper.java:210)
                         E      at android.os.Looper.loop(Looper.java:299)
                         E      at android.app.ActivityThread.main(ActivityThread.java:8105)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
                         E  Caused by: android.os.DeadObjectException
                         E      at android.os.BinderProxy.transactNative(Native Method)
                         E      at android.os.BinderProxy.transact(BinderProxy.java:624)
                         E      at android.view.IWindowSession$Stub$Proxy.addToDisplayAsUser(IWindowSession.java:1368)
                         E      at android.view.ViewRootImpl.setView(ViewRootImpl.java:1190)
                         E      ... 21 more
                flutter  I  ----------------FIREBASE CRASHLYTICS----------------
                         I  PlatformException(error, Adding window failed, null, java.lang.RuntimeException: Adding window failed
                         I      at android.view.ViewRootImpl.setView(ViewRootImpl.java:1205)
                         I      at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:403)
                         I      at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:134)
                         I      at android.app.Dialog.show(Dialog.java:354)
                         I      at android.app.Presentation.show(Presentation.java:279)
                         I      at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:119)
                         I      at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:64)
                         I      at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:267)
                         I      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
                         I      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
                         I      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Met
                         I  #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
                         I  #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
                         I  <asynchronous suspension>
                         I  #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1146:18)
                         I  <asynchronous suspension>
                         I  #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:792:5)
                         I  <asynchronous suspension>
                         I  #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:819:7)
                         I  <asynchronous suspension>
                         I  #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:182:29)
                         I  <asynchronous suspension>
                         I  ----------------------------------------------------`

**Comment by ygit** [comment]
@Nasseh123 Can you share the Room Meeting Link you are using to join?

**Comment by Nasseh123** [comment]
Here https://sstream.app.100ms.live/preview/ntu-uky-iwf
